# .github/workflows/ci.yml

name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # go-versionを指定せず、go.modからバージョンを読み込むようにします
    - name: Set up Go
      uses: actions/setup-go@v5

    # ★★★ このステップを追加 ★★★
    # go.modファイルに基づいて依存関係をダウンロードし、go.sumを更新します
    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v -o myapp .

    # ... (必要に応じてテスト等のステップ)